### ISSUE TITLE
e4mc is incompatible with xaerosmap

### ISSUE THREAD

**Issue by mousebute** [vgskye/e4mc.link#2]
Minecraft 1.20.1 fabric 
last version e4mc

I installed this mod in my minecraft build. I was playing with friends, but then when we started playing the second time, they erased the entire xaerosmap map. most likely, this is due to the fact that the server domain is changing, which is why the map is changing. Is there any solution to this problem??

**Comment by vgskye** [comment]
1) wrong repo
2) working as intended, e4mc intentionally stores no state anywhere
